version: '2'
services:

    secrets:
        build:
            context: .
            args:
                TZ: America/Chicago

        image: umputun/secrets:latest
        container_name: secrets
        hostname: secrets
        restart: always
        volumes:
            - ./var:/data

    nginx:
        build: nginx
        image: umputun/secrets:nginx
        hostname: nginx
        restart: always
        container_name: nginx

        depends_on:
            - secrets

        volumes:
            - ./etc/ssl:/etc/nginx/ssl

        volumes_from:
            - secrets

        ports:
            - "80:80"
            - "443:443"
